version: '3.8'
services:
  top.api:
    image: ghcr.io/emptyladen/top-api-demo/top-api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
