version: '3.8'
services:
  top.api:
    image: docker.pkg.github.com/emptyladen/top-api-demo/top-api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
